source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftInjections_Example', :exclusive => true do
  pod "SwiftInjections", :path => "../"
end

target 'SwiftInjections_Tests', :exclusive => true do
  pod "SwiftInjections", :path => "../"

  
end
